
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # If you are using pnpm, uncomment the following lines
          # cache: 'pnpm'

      # If you are using pnpm, install it
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      - name: Install Dependencies
        run: npm install # or pnpm install or yarn install

      - name: Build 🏗️
        run: npm run build # or pnpm build or yarn build

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
